<?php
include_once "../Model/Compte.class.php";
include_once "../Model/Client.class.php";

echo "◄===================================================►\n";
echo "◄===================================================►\n\n\n";
echo "Compte 1 : \n\n";
$cin = readline("Donnez votre numéro de CIN : ");
$nom = readline("Donnez votre Nom : ");
$prenom = readline("Donnez votre Prénom : ");
$tel = readline("Donnez votre numéro de Téléphone : ");
echo "\n\n";
echo "◄===================================================►\n";
echo "◄===================================================►\n";
$compte = new Compte($cin,$nom,$prenom,$tel);
$affichage1 = $compte->affichage();
echo $affichage1;
echo "\n\n";
echo "◄===================================================►\n";
echo "◄===================================================►\n\n\n";
$solde = readline("Entrez le montant à créditer : ");
$compte->crediter($solde);
echo "◄===================================================►\n";
echo "◄===================================================►\n\n\n";
$affichage1 = $compte->affichage();
echo $affichage1;
echo "\n\n";
echo "◄===================================================►\n";
echo "◄===================================================►\n\n\n";
$solde = readline("Entrez le montant à débiter : ");
$compte->debiter($solde);
echo "◄===================================================►\n";
echo "◄===================================================►\n\n\n";
$affichage1 = $compte->affichage();
echo $affichage1;
echo "\n\n";
echo "◄===================================================►\n";
echo "◄===================================================►\n\n\n";
echo "Compte 2 : \n\n";
$cin = readline("Donnez votre numéro de CIN : ");
$nom = readline("Donnez votre Nom : ");
$prenom = readline("Donnez votre Prénom : ");
$tel = readline("Donnez votre numéro de Téléphone : ");
echo "\n\n";
echo "◄===================================================►\n";
echo "◄===================================================►\n";
$compte2 = new Compte($cin,$nom,$prenom,$tel);
$affichage2 = $compte2->affichage();
echo $affichage2;
echo "\n\n";
echo "◄===================================================►\n";
echo "◄===================================================►\n\n\n";
echo "Créditer le compte 2 à partir du compte 1\n";
$solde = readline("Donnez le montant à créditer :");
$compte->crediterCpt($solde,$compte2);
echo "\n\n";
echo "◄===================================================►\n";
echo "◄===================================================►\n\n\n";
echo "Débiter le compte 1 et créditer le compte 2\n";
$solde = readline("Donnez le montant à débiter :");
$compte2->debiterCpt($solde,$compte);
echo "\n\n";
echo "◄===================================================►\n";
echo "◄===================================================►\n";
$affichage3 = $compte->affichageResume1();
echo $affichage3;
echo "\n\n";
echo "◄===================================================►\n";
echo "◄===================================================►\n";
$affichage4 = $compte2->affichageResume2();
echo $affichage4;
echo "\n\n";
echo "◄===================================================►\n";
echo "◄===================================================►\n\n\n";
$total = $compte->getCode();
echo "Le nombre de compte crée est de : $total\n";
echo "\n\n";
echo "◄===================================================►\n";
echo "◄===================================================►\n\n";